### ISSUE TITLE
Include your app with F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [Dryec/tron-wallet-android#2]
Free and privacy-friendly Android apps belong to F-Droid :wink: So I hope you'd welcome to have your app listed there? Assuming your agreement, I've already [opened a request for packaging](https://gitlab.com/fdroid/rfp/issues/612). Be welcome to chime in there!

Until your app becomes available in the prestiguous official repository, I've already [included it with mine](https://apt.izzysoft.de/fdroid/index/apk/com.eletac.tronwallet). Hope both is OK with you?

**Comment by Dryec** [comment]
Yeah, of course, why not!
